-- Economic Calendar Phase 2A — seed data, generated from src/data/economicCalendarEvents.ts
-- by scripts/generateEconomicCalendarSeed.ts. Regenerate this file (do not hand-edit) whenever
-- the mock data changes. Run AFTER 0002_economic_calendar_events.sql, in the Supabase SQL editor.
-- Every INSERT is an idempotent upsert (ON CONFLICT ... DO UPDATE), so re-running this file is safe.

-- 13 series, 36 events.

insert into public.economic_event_series (slug, title, category, default_importance, cadence, source_name, source_url, automation_tier, reliability_score, description)
values ('spi-weekly-inflation-release', 'SPI Weekly Inflation Release', 'Inflation', 'Low', 'weekly', 'Pakistan Bureau of Statistics', 'https://www.pbs.gov.pk/spi', 'automated', 4, 'PBS''s weekly Sensitive Price Indicator — a fast-moving read on prices for a basket of essential, frequently-purchased items, well ahead of the monthly CPI print.')
on conflict (slug) do update set title = excluded.title, category = excluded.category, default_importance = excluded.default_importance, cadence = excluded.cadence, source_name = excluded.source_name, source_url = excluded.source_url, automation_tier = excluded.automation_tier, reliability_score = excluded.reliability_score, description = excluded.description, updated_at = now();
insert into public.economic_event_series (slug, title, category, default_importance, cadence, source_name, source_url, automation_tier, reliability_score, description)
values ('sbp-foreign-exchange-reserves', 'SBP Foreign Exchange Reserves', 'External Sector', 'Medium', 'weekly', 'State Bank of Pakistan', 'https://www.sbp.org.pk/ecodata/index2.asp', 'automated', 5, 'The State Bank''s weekly statement of liquid foreign reserves — the buffer available to defend the Rupee and meet external obligations.')
on conflict (slug) do update set title = excluded.title, category = excluded.category, default_importance = excluded.default_importance, cadence = excluded.cadence, source_name = excluded.source_name, source_url = excluded.source_url, automation_tier = excluded.automation_tier, reliability_score = excluded.reliability_score, description = excluded.description, updated_at = now();
insert into public.economic_event_series (slug, title, category, default_importance, cadence, source_name, source_url, automation_tier, reliability_score, description)
values ('kse-100-weekly-market-review', 'KSE-100 Weekly Market Review', 'Financial Markets', 'Low', 'weekly', 'Pakistan Stock Exchange', 'https://www.psx.com.pk/', 'semi_automated', 4, 'A weekly wrap-up of the Pakistan Stock Exchange''s benchmark KSE-100 index performance and the sectors driving it.')
on conflict (slug) do update set title = excluded.title, category = excluded.category, default_importance = excluded.default_importance, cadence = excluded.cadence, source_name = excluded.source_name, source_url = excluded.source_url, automation_tier = excluded.automation_tier, reliability_score = excluded.reliability_score, description = excluded.description, updated_at = now();
insert into public.economic_event_series (slug, title, category, default_importance, cadence, source_name, source_url, automation_tier, reliability_score, description)
values ('oil-price-update', 'Oil Price Update', 'Global Events', 'Low', 'monthly', 'OPEC', null, 'semi_automated', 3, 'OPEC''s monthly oil market report — global crude prices feed directly into Pakistan''s import bill and fuel-linked inflation.')
on conflict (slug) do update set title = excluded.title, category = excluded.category, default_importance = excluded.default_importance, cadence = excluded.cadence, source_name = excluded.source_name, source_url = excluded.source_url, automation_tier = excluded.automation_tier, reliability_score = excluded.reliability_score, description = excluded.description, updated_at = now();
insert into public.economic_event_series (slug, title, category, default_importance, cadence, source_name, source_url, automation_tier, reliability_score, description)
values ('trade-balance', 'Trade Balance', 'External Sector', 'Medium', 'monthly', 'Pakistan Bureau of Statistics', 'https://www.pbs.gov.pk/', 'automated', 4, 'PBS''s monthly goods trade balance — exports minus imports — one of the clearest signals of pressure on the Rupee and reserves.')
on conflict (slug) do update set title = excluded.title, category = excluded.category, default_importance = excluded.default_importance, cadence = excluded.cadence, source_name = excluded.source_name, source_url = excluded.source_url, automation_tier = excluded.automation_tier, reliability_score = excluded.reliability_score, description = excluded.description, updated_at = now();
insert into public.economic_event_series (slug, title, category, default_importance, cadence, source_name, source_url, automation_tier, reliability_score, description)
values ('cpi-inflation-release', 'CPI Inflation Release', 'Inflation', 'High', 'monthly', 'Pakistan Bureau of Statistics', 'https://www.pbs.gov.pk/cpi', 'semi_automated', 3, 'PBS''s headline Consumer Price Index — the most-watched single inflation number, and the figure SBP weighs most heavily when setting the policy rate.')
on conflict (slug) do update set title = excluded.title, category = excluded.category, default_importance = excluded.default_importance, cadence = excluded.cadence, source_name = excluded.source_name, source_url = excluded.source_url, automation_tier = excluded.automation_tier, reliability_score = excluded.reliability_score, description = excluded.description, updated_at = now();
insert into public.economic_event_series (slug, title, category, default_importance, cadence, source_name, source_url, automation_tier, reliability_score, description)
values ('current-account-balance', 'Current Account Balance', 'External Sector', 'High', 'monthly', 'State Bank of Pakistan', 'https://www.sbp.org.pk/ecodata/index2.asp', 'automated', 4, 'SBP''s monthly current account balance — the broadest measure of money flowing in versus out of Pakistan internationally, and a key driver of reserve and currency stability.')
on conflict (slug) do update set title = excluded.title, category = excluded.category, default_importance = excluded.default_importance, cadence = excluded.cadence, source_name = excluded.source_name, source_url = excluded.source_url, automation_tier = excluded.automation_tier, reliability_score = excluded.reliability_score, description = excluded.description, updated_at = now();
insert into public.economic_event_series (slug, title, category, default_importance, cadence, source_name, source_url, automation_tier, reliability_score, description)
values ('worker-remittances', 'Worker Remittances', 'External Sector', 'Medium', 'monthly', 'State Bank of Pakistan', 'https://www.sbp.org.pk/ecodata/homeremit.pdf', 'automated', 4, 'SBP''s monthly worker remittance inflows — money sent home by overseas Pakistanis, a major source of foreign exchange alongside exports.')
on conflict (slug) do update set title = excluded.title, category = excluded.category, default_importance = excluded.default_importance, cadence = excluded.cadence, source_name = excluded.source_name, source_url = excluded.source_url, automation_tier = excluded.automation_tier, reliability_score = excluded.reliability_score, description = excluded.description, updated_at = now();
insert into public.economic_event_series (slug, title, category, default_importance, cadence, source_name, source_url, automation_tier, reliability_score, description)
values ('sbp-monetary-policy-committee-meeting', 'SBP Monetary Policy Committee Meeting', 'Monetary Policy', 'High', 'irregular', 'State Bank of Pakistan', 'https://www.sbp.org.pk/m_policy/mp-calendar.asp', 'semi_automated', 5, 'The State Bank''s policy rate decision — the single most market-moving recurring event on this calendar, setting the benchmark cost of borrowing across the economy.')
on conflict (slug) do update set title = excluded.title, category = excluded.category, default_importance = excluded.default_importance, cadence = excluded.cadence, source_name = excluded.source_name, source_url = excluded.source_url, automation_tier = excluded.automation_tier, reliability_score = excluded.reliability_score, description = excluded.description, updated_at = now();
insert into public.economic_event_series (slug, title, category, default_importance, cadence, source_name, source_url, automation_tier, reliability_score, description)
values ('us-federal-reserve-fomc-meeting-decision', 'US Federal Reserve FOMC Meeting Decision', 'Global Events', 'High', 'irregular', 'US Federal Reserve', 'https://www.federalreserve.gov/', 'semi_automated', 4, 'The Fed''s interest rate decision moves global capital flows and the Dollar broadly — a hike or cut shifts the relative appeal of holding Rupee versus Dollar assets.')
on conflict (slug) do update set title = excluded.title, category = excluded.category, default_importance = excluded.default_importance, cadence = excluded.cadence, source_name = excluded.source_name, source_url = excluded.source_url, automation_tier = excluded.automation_tier, reliability_score = excluded.reliability_score, description = excluded.description, updated_at = now();
insert into public.economic_event_series (slug, title, category, default_importance, cadence, source_name, source_url, automation_tier, reliability_score, description)
values ('gdp-growth-release', 'GDP Growth Release', 'Real Economy', 'High', 'quarterly', 'Pakistan Bureau of Statistics', 'https://www.pbs.gov.pk/national-accounts-2/', 'semi_automated', 5, 'PBS''s provisional annual GDP growth estimate — the headline number used to judge whether the economy is creating jobs and raising incomes fast enough.')
on conflict (slug) do update set title = excluded.title, category = excluded.category, default_importance = excluded.default_importance, cadence = excluded.cadence, source_name = excluded.source_name, source_url = excluded.source_url, automation_tier = excluded.automation_tier, reliability_score = excluded.reliability_score, description = excluded.description, updated_at = now();
insert into public.economic_event_series (slug, title, category, default_importance, cadence, source_name, source_url, automation_tier, reliability_score, description)
values ('pakistan-economic-survey', 'Pakistan Economic Survey', 'Fiscal Sector', 'High', 'annual', 'Ministry of Finance', 'https://www.finance.gov.pk/', 'manual', 2, 'The Ministry of Finance''s annual stock-take of the economy — growth, inflation, fiscal and external accounts — released the day before the federal budget and used to frame it.')
on conflict (slug) do update set title = excluded.title, category = excluded.category, default_importance = excluded.default_importance, cadence = excluded.cadence, source_name = excluded.source_name, source_url = excluded.source_url, automation_tier = excluded.automation_tier, reliability_score = excluded.reliability_score, description = excluded.description, updated_at = now();
insert into public.economic_event_series (slug, title, category, default_importance, cadence, source_name, source_url, automation_tier, reliability_score, description)
values ('federal-budget', 'Federal Budget', 'Fiscal Sector', 'High', 'annual', 'Ministry of Finance', 'https://www.finance.gov.pk/', 'manual', 2, 'The federal government''s annual budget speech in the National Assembly — next year''s tax measures, spending allocations, and fiscal targets, all set in this single sitting.')
on conflict (slug) do update set title = excluded.title, category = excluded.category, default_importance = excluded.default_importance, cadence = excluded.cadence, source_name = excluded.source_name, source_url = excluded.source_url, automation_tier = excluded.automation_tier, reliability_score = excluded.reliability_score, description = excluded.description, updated_at = now();

insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'spi-weekly-inflation-release'), 'spi-2026-06-27', 'SPI Weekly Inflation Release', '2026-06-27', '12:00', '+0.31% WoW', '+0.25% WoW', null, 'scheduled', 'Low', 'PBS''s weekly Sensitive Price Indicator — a fast-moving read on prices for a basket of essential, frequently-purchased items, well ahead of the monthly CPI print.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'sbp-foreign-exchange-reserves'), 'fx-reserves-2026-06-29', 'SBP Foreign Exchange Reserves (Weekly)', '2026-06-29', '16:30', '$11.2B', '$11.4B', null, 'scheduled', 'Medium', 'The State Bank''s weekly statement of liquid foreign reserves — the buffer available to defend the Rupee and meet external obligations.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'kse-100-weekly-market-review'), 'kse-2026-06-30', 'KSE-100 Weekly Market Review', '2026-06-30', '17:00', '+1.8% WoW', null, null, 'scheduled', 'Low', 'A weekly wrap-up of the Pakistan Stock Exchange''s benchmark KSE-100 index performance and the sectors driving it.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'oil-price-update'), 'oil-2026-07-01', 'Oil Price Update (OPEC Monthly Report)', '2026-07-01', '15:00', '$83.40/bbl', '$84.00/bbl', null, 'scheduled', 'Low', 'OPEC''s monthly oil market report — global crude prices feed directly into Pakistan''s import bill and fuel-linked inflation.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'spi-weekly-inflation-release'), 'spi-2026-07-02', 'SPI Weekly Inflation Release', '2026-07-02', '12:00', '+0.25% WoW', '+0.20% WoW', null, 'scheduled', 'Low', 'PBS''s weekly Sensitive Price Indicator — a fast-moving read on prices for a basket of essential, frequently-purchased items, well ahead of the monthly CPI print.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'trade-balance'), 'trade-balance-2026-07-03', 'Trade Balance (June 2026)', '2026-07-03', '17:00', '-$2.1B', '-$1.9B', null, 'scheduled', 'Medium', 'PBS''s monthly goods trade balance — exports minus imports — one of the clearest signals of pressure on the Rupee and reserves.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'sbp-foreign-exchange-reserves'), 'fx-reserves-2026-07-05', 'SBP Foreign Exchange Reserves (Weekly)', '2026-07-05', '16:30', '$11.4B', '$11.5B', null, 'scheduled', 'Medium', 'The State Bank''s weekly statement of liquid foreign reserves — the buffer available to defend the Rupee and meet external obligations.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'kse-100-weekly-market-review'), 'kse-2026-07-07', 'KSE-100 Weekly Market Review', '2026-07-07', '17:00', '+0.6% WoW', null, null, 'scheduled', 'Low', 'A weekly wrap-up of the Pakistan Stock Exchange''s benchmark KSE-100 index performance and the sectors driving it.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'spi-weekly-inflation-release'), 'spi-2026-07-09', 'SPI Weekly Inflation Release', '2026-07-09', '12:00', '+0.20% WoW', '+0.18% WoW', null, 'scheduled', 'Low', 'PBS''s weekly Sensitive Price Indicator — a fast-moving read on prices for a basket of essential, frequently-purchased items, well ahead of the monthly CPI print.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'cpi-inflation-release'), 'cpi-2026-07-10', 'CPI Inflation Release (June 2026)', '2026-07-10', '12:00', '6.8% YoY', '6.4% YoY', null, 'scheduled', 'High', 'PBS''s headline Consumer Price Index — the most-watched single inflation number, and the figure SBP weighs most heavily when setting the policy rate.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'sbp-foreign-exchange-reserves'), 'fx-reserves-2026-07-12', 'SBP Foreign Exchange Reserves (Weekly)', '2026-07-12', '16:30', '$11.5B', '$11.6B', null, 'scheduled', 'Medium', 'The State Bank''s weekly statement of liquid foreign reserves — the buffer available to defend the Rupee and meet external obligations.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'current-account-balance'), 'current-account-2026-07-15', 'Current Account Balance (June 2026)', '2026-07-15', '17:00', '-$0.4B', '-$0.2B', null, 'scheduled', 'High', 'SBP''s monthly current account balance — the broadest measure of money flowing in versus out of Pakistan internationally, and a key driver of reserve and currency stability.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'spi-weekly-inflation-release'), 'spi-2026-07-16', 'SPI Weekly Inflation Release', '2026-07-16', '12:00', '+0.18% WoW', '+0.15% WoW', null, 'scheduled', 'Low', 'PBS''s weekly Sensitive Price Indicator — a fast-moving read on prices for a basket of essential, frequently-purchased items, well ahead of the monthly CPI print.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'worker-remittances'), 'remittances-2026-07-18', 'Worker Remittances (June 2026)', '2026-07-18', '16:00', '$3.1B', '$3.2B', null, 'scheduled', 'Medium', 'SBP''s monthly worker remittance inflows — money sent home by overseas Pakistanis, a major source of foreign exchange alongside exports.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'sbp-foreign-exchange-reserves'), 'fx-reserves-2026-07-19', 'SBP Foreign Exchange Reserves (Weekly)', '2026-07-19', '16:30', '$11.6B', '$11.7B', null, 'scheduled', 'Medium', 'The State Bank''s weekly statement of liquid foreign reserves — the buffer available to defend the Rupee and meet external obligations.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'kse-100-weekly-market-review'), 'kse-2026-07-21', 'KSE-100 Weekly Market Review', '2026-07-21', '17:00', '-0.4% WoW', null, null, 'scheduled', 'Low', 'A weekly wrap-up of the Pakistan Stock Exchange''s benchmark KSE-100 index performance and the sectors driving it.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'sbp-monetary-policy-committee-meeting'), 'sbp-mpc-2026-07-22', 'SBP Monetary Policy Committee Meeting', '2026-07-22', '14:00', '11.0%', '11.0% (hold expected)', null, 'scheduled', 'High', 'The State Bank''s policy rate decision — the single most market-moving recurring event on this calendar, setting the benchmark cost of borrowing across the economy.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'spi-weekly-inflation-release'), 'spi-2026-07-23', 'SPI Weekly Inflation Release', '2026-07-23', '12:00', '+0.15% WoW', '+0.14% WoW', null, 'scheduled', 'Low', 'PBS''s weekly Sensitive Price Indicator — a fast-moving read on prices for a basket of essential, frequently-purchased items, well ahead of the monthly CPI print.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'sbp-foreign-exchange-reserves'), 'fx-reserves-2026-07-26', 'SBP Foreign Exchange Reserves (Weekly)', '2026-07-26', '16:30', '$11.7B', '$11.8B', null, 'scheduled', 'Medium', 'The State Bank''s weekly statement of liquid foreign reserves — the buffer available to defend the Rupee and meet external obligations.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'us-federal-reserve-fomc-meeting-decision'), 'fomc-2026-07-29', 'US Federal Reserve FOMC Meeting Decision', '2026-07-29', '23:00', '4.25%-4.50%', '4.25%-4.50% (hold expected)', null, 'scheduled', 'High', 'The Fed''s interest rate decision moves global capital flows and the Dollar broadly — a hike or cut shifts the relative appeal of holding Rupee versus Dollar assets.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'spi-weekly-inflation-release'), 'spi-2026-07-30', 'SPI Weekly Inflation Release', '2026-07-30', '12:00', '+0.14% WoW', '+0.12% WoW', null, 'scheduled', 'Low', 'PBS''s weekly Sensitive Price Indicator — a fast-moving read on prices for a basket of essential, frequently-purchased items, well ahead of the monthly CPI print.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'trade-balance'), 'trade-balance-2026-07-31', 'Trade Balance (July 2026)', '2026-07-31', '17:00', '-$1.9B', '-$2.0B', null, 'scheduled', 'Medium', 'PBS''s monthly goods trade balance — exports minus imports — one of the clearest signals of pressure on the Rupee and reserves.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'sbp-foreign-exchange-reserves'), 'fx-reserves-2026-08-02', 'SBP Foreign Exchange Reserves (Weekly)', '2026-08-02', '16:30', '$11.8B', '$11.9B', null, 'scheduled', 'Medium', 'The State Bank''s weekly statement of liquid foreign reserves — the buffer available to defend the Rupee and meet external obligations.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'gdp-growth-release'), 'gdp-2026-08-07', 'GDP Growth Release (FY2025-26 Provisional)', '2026-08-07', '16:00', '2.7%', '3.2%', null, 'scheduled', 'High', 'PBS''s provisional annual GDP growth estimate — the headline number used to judge whether the economy is creating jobs and raising incomes fast enough.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'cpi-inflation-release'), 'cpi-2026-08-10', 'CPI Inflation Release (July 2026)', '2026-08-10', '12:00', '6.4% YoY', '6.1% YoY', null, 'scheduled', 'High', 'PBS''s headline Consumer Price Index — the most-watched single inflation number, and the figure SBP weighs most heavily when setting the policy rate.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'current-account-balance'), 'current-account-2026-08-14', 'Current Account Balance (July 2026)', '2026-08-14', '17:00', '-$0.2B', '-$0.3B', null, 'scheduled', 'High', 'SBP''s monthly current account balance — the broadest measure of money flowing in versus out of Pakistan internationally, and a key driver of reserve and currency stability.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'sbp-monetary-policy-committee-meeting'), 'sbp-mpc-2026-09-09', 'SBP Monetary Policy Committee Meeting', '2026-09-09', '14:00', '11.0%', '10.75%', null, 'scheduled', 'High', 'The State Bank''s policy rate decision — the single most market-moving recurring event on this calendar, setting the benchmark cost of borrowing across the economy.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'pakistan-economic-survey'), 'economic-survey-2027-06-05', 'Pakistan Economic Survey 2026-27', '2027-06-05', '15:00', 'Economic Survey 2025-26', null, null, 'scheduled', 'High', 'The Ministry of Finance''s annual stock-take of the economy — growth, inflation, fiscal and external accounts — released the day before the federal budget and used to frame it.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'federal-budget'), 'federal-budget-2027-06-06', 'Federal Budget 2027-28 Presentation', '2027-06-06', '17:00', 'Federal Budget 2026-27', null, null, 'scheduled', 'High', 'The federal government''s annual budget speech in the National Assembly — next year''s tax measures, spending allocations, and fiscal targets, all set in this single sitting.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'cpi-inflation-release'), 'cpi-2026-04-10', 'CPI Inflation Release (April 2026)', '2026-04-10', '12:00', '7.4% YoY', '7.0% YoY', '7.1% YoY', 'released', 'High', 'PBS''s headline Consumer Price Index — the most-watched single inflation number, and the figure SBP weighs most heavily when setting the policy rate.', 'confirmed')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'gdp-growth-release'), 'gdp-2026-04-15', 'GDP Growth Release (FY2024-25 Final)', '2026-04-15', '16:00', '2.62%', '3.0%', '3.18%', 'released', 'High', 'PBS''s final, revised annual GDP growth figure for FY2024-25 — the headline number used to judge whether the economy is creating jobs and raising incomes fast enough.', 'confirmed')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'sbp-monetary-policy-committee-meeting'), 'sbp-mpc-2026-04-27', 'SBP Monetary Policy Committee Meeting', '2026-04-27', '14:00', '11.0%', '11.0% (hold expected)', '11.0% (held)', 'released', 'High', 'The State Bank''s policy rate decision — the single most market-moving recurring event on this calendar, setting the benchmark cost of borrowing across the economy.', 'confirmed')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'current-account-balance'), 'current-account-2026-05-15', 'Current Account Balance (April 2026)', '2026-05-15', '17:00', '-$0.6B', '-$0.4B', '-$0.5B', 'released', 'High', 'SBP''s monthly current account balance — the broadest measure of money flowing in versus out of Pakistan internationally, and a key driver of reserve and currency stability.', 'confirmed')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'cpi-inflation-release'), 'cpi-2026-05-10', 'CPI Inflation Release (May 2026)', '2026-05-10', '12:00', '7.1% YoY', '6.9% YoY', '6.8% YoY', 'released', 'High', 'PBS''s headline Consumer Price Index — the most-watched single inflation number, and the figure SBP weighs most heavily when setting the policy rate.', 'confirmed')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'sbp-monetary-policy-committee-meeting'), 'sbp-mpc-2026-06-15', 'SBP Monetary Policy Committee Meeting', '2026-06-15', '14:00', '11.0%', '11.0% (hold expected)', '11.0% (held)', 'released', 'High', 'The State Bank''s policy rate decision — the single most market-moving recurring event on this calendar, setting the benchmark cost of borrowing across the economy.', 'confirmed')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'sbp-foreign-exchange-reserves'), 'fx-reserves-2026-06-18', 'SBP Foreign Exchange Reserves (Weekly)', '2026-06-18', '16:30', '$10.9B', '$11.0B', '$11.0B', 'released', 'Medium', 'The State Bank''s weekly statement of liquid foreign reserves — the buffer available to defend the Rupee and meet external obligations.', 'confirmed')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
