-- Economic Calendar Phase 2A — seed data, generated from src/data/economicCalendarEvents.ts
-- by scripts/generateEconomicCalendarSeed.ts. Regenerate this file (do not hand-edit) whenever
-- the mock data changes. Run AFTER 0002_economic_calendar_events.sql, in the Supabase SQL editor.
-- Every INSERT is an idempotent upsert (ON CONFLICT ... DO UPDATE), so re-running this file is safe.

-- 17 series, 51 events.

insert into public.economic_event_series (slug, title, category, default_importance, cadence, source_name, source_url, automation_tier, reliability_score, description)
values ('spi-weekly-inflation-release', 'SPI Weekly Inflation Release', 'Inflation', 'Low', 'weekly', 'Pakistan Bureau of Statistics', 'https://www.pbs.gov.pk/spi', 'semi_automated', 4, 'PBS''s weekly Sensitive Price Indicator — a fast-moving read on prices for a basket of essential, frequently-purchased items, well ahead of the monthly CPI print.')
on conflict (slug) do update set title = excluded.title, category = excluded.category, default_importance = excluded.default_importance, cadence = excluded.cadence, source_name = excluded.source_name, source_url = excluded.source_url, automation_tier = excluded.automation_tier, reliability_score = excluded.reliability_score, description = excluded.description, updated_at = now();
insert into public.economic_event_series (slug, title, category, default_importance, cadence, source_name, source_url, automation_tier, reliability_score, description)
values ('sbp-foreign-exchange-reserves', 'SBP Foreign Exchange Reserves', 'External Sector', 'Medium', 'weekly', 'State Bank of Pakistan', 'https://www.sbp.org.pk/ecodata/index2.asp', 'automated', 5, 'The State Bank''s weekly statement of liquid foreign reserves — the buffer available to defend the Rupee and meet external obligations.')
on conflict (slug) do update set title = excluded.title, category = excluded.category, default_importance = excluded.default_importance, cadence = excluded.cadence, source_name = excluded.source_name, source_url = excluded.source_url, automation_tier = excluded.automation_tier, reliability_score = excluded.reliability_score, description = excluded.description, updated_at = now();
insert into public.economic_event_series (slug, title, category, default_importance, cadence, source_name, source_url, automation_tier, reliability_score, description)
values ('kse-100-weekly-market-review', 'KSE-100 Weekly Market Review', 'Financial Markets', 'Low', 'weekly', 'Pakistan Stock Exchange', 'https://www.psx.com.pk/', 'semi_automated', 4, 'A weekly wrap-up of the Pakistan Stock Exchange''s benchmark KSE-100 index performance and the sectors driving it.')
on conflict (slug) do update set title = excluded.title, category = excluded.category, default_importance = excluded.default_importance, cadence = excluded.cadence, source_name = excluded.source_name, source_url = excluded.source_url, automation_tier = excluded.automation_tier, reliability_score = excluded.reliability_score, description = excluded.description, updated_at = now();
insert into public.economic_event_series (slug, title, category, default_importance, cadence, source_name, source_url, automation_tier, reliability_score, description)
values ('trade-balance', 'Trade Balance', 'External Sector', 'Medium', 'monthly', 'Pakistan Bureau of Statistics', 'https://www.pbs.gov.pk/', 'automated', 4, 'PBS''s monthly goods trade balance — exports minus imports — one of the clearest signals of pressure on the Rupee and reserves.')
on conflict (slug) do update set title = excluded.title, category = excluded.category, default_importance = excluded.default_importance, cadence = excluded.cadence, source_name = excluded.source_name, source_url = excluded.source_url, automation_tier = excluded.automation_tier, reliability_score = excluded.reliability_score, description = excluded.description, updated_at = now();
insert into public.economic_event_series (slug, title, category, default_importance, cadence, source_name, source_url, automation_tier, reliability_score, description)
values ('cpi-inflation-release', 'CPI Inflation Release', 'Inflation', 'High', 'monthly', 'Pakistan Bureau of Statistics', 'https://www.pbs.gov.pk/cpi', 'automated', 4, 'PBS''s headline Consumer Price Index — the most-watched single inflation number, and the figure SBP weighs most heavily when setting the policy rate.')
on conflict (slug) do update set title = excluded.title, category = excluded.category, default_importance = excluded.default_importance, cadence = excluded.cadence, source_name = excluded.source_name, source_url = excluded.source_url, automation_tier = excluded.automation_tier, reliability_score = excluded.reliability_score, description = excluded.description, updated_at = now();
insert into public.economic_event_series (slug, title, category, default_importance, cadence, source_name, source_url, automation_tier, reliability_score, description)
values ('current-account-balance', 'Current Account Balance', 'External Sector', 'Medium', 'monthly', 'State Bank of Pakistan', 'https://www.sbp.org.pk/ecodata/index2.asp', 'automated', 4, 'SBP''s monthly current account balance — the broadest measure of money flowing in versus out of Pakistan internationally, and a key driver of reserve and currency stability.')
on conflict (slug) do update set title = excluded.title, category = excluded.category, default_importance = excluded.default_importance, cadence = excluded.cadence, source_name = excluded.source_name, source_url = excluded.source_url, automation_tier = excluded.automation_tier, reliability_score = excluded.reliability_score, description = excluded.description, updated_at = now();
insert into public.economic_event_series (slug, title, category, default_importance, cadence, source_name, source_url, automation_tier, reliability_score, description)
values ('worker-remittances', 'Worker Remittances', 'External Sector', 'Medium', 'monthly', 'State Bank of Pakistan', 'https://www.sbp.org.pk/ecodata/homeremit.pdf', 'automated', 4, 'SBP''s monthly worker remittance inflows — money sent home by overseas Pakistanis, a major source of foreign exchange alongside exports.')
on conflict (slug) do update set title = excluded.title, category = excluded.category, default_importance = excluded.default_importance, cadence = excluded.cadence, source_name = excluded.source_name, source_url = excluded.source_url, automation_tier = excluded.automation_tier, reliability_score = excluded.reliability_score, description = excluded.description, updated_at = now();
insert into public.economic_event_series (slug, title, category, default_importance, cadence, source_name, source_url, automation_tier, reliability_score, description)
values ('sbp-monetary-policy-committee-meeting', 'SBP Monetary Policy Committee Meeting', 'Monetary Policy', 'High', 'irregular', 'State Bank of Pakistan', 'https://www.sbp.org.pk/m_policy/mp-calendar.asp', 'automated', 5, 'The State Bank''s policy rate decision — the single most market-moving recurring event on this calendar, setting the benchmark cost of borrowing across the economy. First MPC meeting of FY27, per SBP''s official advance calendar; same-day Monetary Policy Statement, analyst briefing the following day (Jul 28), and SBP''s first Monetary Policy Report of FY27 due Aug 10.')
on conflict (slug) do update set title = excluded.title, category = excluded.category, default_importance = excluded.default_importance, cadence = excluded.cadence, source_name = excluded.source_name, source_url = excluded.source_url, automation_tier = excluded.automation_tier, reliability_score = excluded.reliability_score, description = excluded.description, updated_at = now();
insert into public.economic_event_series (slug, title, category, default_importance, cadence, source_name, source_url, automation_tier, reliability_score, description)
values ('gdp-growth-release', 'GDP Growth Release', 'Real Economy', 'High', 'quarterly', 'Pakistan Bureau of Statistics', 'https://www.pbs.gov.pk/national-accounts-2/', 'semi_automated', 5, 'PBS''s provisional annual GDP growth estimate — the headline number used to judge whether the economy is creating jobs and raising incomes fast enough.')
on conflict (slug) do update set title = excluded.title, category = excluded.category, default_importance = excluded.default_importance, cadence = excluded.cadence, source_name = excluded.source_name, source_url = excluded.source_url, automation_tier = excluded.automation_tier, reliability_score = excluded.reliability_score, description = excluded.description, updated_at = now();
insert into public.economic_event_series (slug, title, category, default_importance, cadence, source_name, source_url, automation_tier, reliability_score, description)
values ('pakistan-economic-survey', 'Pakistan Economic Survey', 'Fiscal Sector', 'High', 'annual', 'Ministry of Finance', 'https://www.finance.gov.pk/', 'manual', 2, 'The Ministry of Finance''s annual stock-take of the economy — growth, inflation, fiscal and external accounts — released the day before the federal budget and used to frame it.')
on conflict (slug) do update set title = excluded.title, category = excluded.category, default_importance = excluded.default_importance, cadence = excluded.cadence, source_name = excluded.source_name, source_url = excluded.source_url, automation_tier = excluded.automation_tier, reliability_score = excluded.reliability_score, description = excluded.description, updated_at = now();
insert into public.economic_event_series (slug, title, category, default_importance, cadence, source_name, source_url, automation_tier, reliability_score, description)
values ('federal-budget', 'Federal Budget', 'Fiscal Sector', 'High', 'annual', 'Ministry of Finance', 'https://www.finance.gov.pk/', 'manual', 2, 'The federal government''s annual budget speech in the National Assembly — next year''s tax measures, spending allocations, and fiscal targets, all set in this single sitting.')
on conflict (slug) do update set title = excluded.title, category = excluded.category, default_importance = excluded.default_importance, cadence = excluded.cadence, source_name = excluded.source_name, source_url = excluded.source_url, automation_tier = excluded.automation_tier, reliability_score = excluded.reliability_score, description = excluded.description, updated_at = now();
insert into public.economic_event_series (slug, title, category, default_importance, cadence, source_name, source_url, automation_tier, reliability_score, description)
values ('treasury-bill-auction', 'Treasury Bill Auction', 'Fiscal Sector', 'Medium', 'weekly', 'State Bank of Pakistan', 'https://www.sbp.org.pk/ecodata/index2.asp', 'automated', 4, 'SBP''s fortnightly 3-month Treasury Bill auction — the cut-off yield is the clearest live read on what the market expects from the next SBP policy rate decision.')
on conflict (slug) do update set title = excluded.title, category = excluded.category, default_importance = excluded.default_importance, cadence = excluded.cadence, source_name = excluded.source_name, source_url = excluded.source_url, automation_tier = excluded.automation_tier, reliability_score = excluded.reliability_score, description = excluded.description, updated_at = now();
insert into public.economic_event_series (slug, title, category, default_importance, cadence, source_name, source_url, automation_tier, reliability_score, description)
values ('core-inflation-release', 'Core Inflation Release', 'Inflation', 'High', 'monthly', 'Pakistan Bureau of Statistics / SBP EasyData', 'https://www.pbs.gov.pk/cpi', 'automated', 4, 'PBS''s core (Urban NFNE) inflation — CPI with volatile food and energy prices stripped out, the measure SBP weighs most heavily for the underlying, persistent inflation trend.')
on conflict (slug) do update set title = excluded.title, category = excluded.category, default_importance = excluded.default_importance, cadence = excluded.cadence, source_name = excluded.source_name, source_url = excluded.source_url, automation_tier = excluded.automation_tier, reliability_score = excluded.reliability_score, description = excluded.description, updated_at = now();
insert into public.economic_event_series (slug, title, category, default_importance, cadence, source_name, source_url, automation_tier, reliability_score, description)
values ('large-scale-manufacturing-lsm-growth', 'Large Scale Manufacturing (LSM) Growth', 'Real Economy', 'Medium', 'monthly', 'Pakistan Bureau of Statistics / SBP EasyData', 'https://www.pbs.gov.pk/', 'automated', 4, 'PBS''s Large Scale Manufacturing index — a monthly, timelier proxy for industrial output growth than the annual GDP release.')
on conflict (slug) do update set title = excluded.title, category = excluded.category, default_importance = excluded.default_importance, cadence = excluded.cadence, source_name = excluded.source_name, source_url = excluded.source_url, automation_tier = excluded.automation_tier, reliability_score = excluded.reliability_score, description = excluded.description, updated_at = now();
insert into public.economic_event_series (slug, title, category, default_importance, cadence, source_name, source_url, automation_tier, reliability_score, description)
values ('pib-auction', 'PIB Auction', 'Fiscal Sector', 'Medium', 'monthly', 'State Bank of Pakistan', 'https://www.sbp.org.pk/ecodata/index2.asp', 'automated', 4, 'SBP''s Pakistan Investment Bond auction — the cut-off yield on longer-dated government debt, reflecting investor expectations for inflation and rates further out than T-Bills.')
on conflict (slug) do update set title = excluded.title, category = excluded.category, default_importance = excluded.default_importance, cadence = excluded.cadence, source_name = excluded.source_name, source_url = excluded.source_url, automation_tier = excluded.automation_tier, reliability_score = excluded.reliability_score, description = excluded.description, updated_at = now();
insert into public.economic_event_series (slug, title, category, default_importance, cadence, source_name, source_url, automation_tier, reliability_score, description)
values ('government-debt-release', 'Government Debt Release', 'Fiscal Sector', 'High', 'quarterly', 'State Bank of Pakistan', 'https://www.sbp.org.pk/ecodata/index2.asp', 'semi_automated', 4, 'SBP''s quarterly statement of total government debt — domestic and external combined — a key gauge of fiscal sustainability and future debt-servicing pressure.')
on conflict (slug) do update set title = excluded.title, category = excluded.category, default_importance = excluded.default_importance, cadence = excluded.cadence, source_name = excluded.source_name, source_url = excluded.source_url, automation_tier = excluded.automation_tier, reliability_score = excluded.reliability_score, description = excluded.description, updated_at = now();
insert into public.economic_event_series (slug, title, category, default_importance, cadence, source_name, source_url, automation_tier, reliability_score, description)
values ('psx-holiday-calendar', 'PSX Holiday Calendar', 'Financial Markets', 'Low', 'annual', 'Pakistan Stock Exchange', 'https://www.psx.com.pk/psx/exchange/general/calendar-holidays', 'semi_automated', 4, 'Pakistan Stock Exchange is closed for trading — no KSE-100 session today.')
on conflict (slug) do update set title = excluded.title, category = excluded.category, default_importance = excluded.default_importance, cadence = excluded.cadence, source_name = excluded.source_name, source_url = excluded.source_url, automation_tier = excluded.automation_tier, reliability_score = excluded.reliability_score, description = excluded.description, updated_at = now();

insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'spi-weekly-inflation-release'), 'spi-2026-06-27', 'SPI Weekly Inflation Release', '2026-06-27', '12:00', '+0.31% WoW', '+0.25% WoW', null, 'scheduled', 'Low', 'PBS''s weekly Sensitive Price Indicator — a fast-moving read on prices for a basket of essential, frequently-purchased items, well ahead of the monthly CPI print.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'sbp-foreign-exchange-reserves'), 'fx-reserves-2026-06-29', 'SBP Foreign Exchange Reserves (Weekly)', '2026-06-29', '16:30', '$11.2B', '$11.4B', null, 'scheduled', 'Medium', 'The State Bank''s weekly statement of liquid foreign reserves — the buffer available to defend the Rupee and meet external obligations.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'kse-100-weekly-market-review'), 'kse-2026-06-30', 'KSE-100 Weekly Market Review', '2026-06-30', '17:00', '+1.8% WoW', null, null, 'scheduled', 'Low', 'A weekly wrap-up of the Pakistan Stock Exchange''s benchmark KSE-100 index performance and the sectors driving it.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'spi-weekly-inflation-release'), 'spi-2026-07-02', 'SPI Weekly Inflation Release', '2026-07-02', '12:00', '+0.25% WoW', '+0.20% WoW', null, 'scheduled', 'Low', 'PBS''s weekly Sensitive Price Indicator — a fast-moving read on prices for a basket of essential, frequently-purchased items, well ahead of the monthly CPI print.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'trade-balance'), 'trade-balance-2026-07-03', 'Trade Balance (June 2026)', '2026-07-03', '17:00', '-$2.1B', '-$1.9B', null, 'scheduled', 'Medium', 'PBS''s monthly goods trade balance — exports minus imports — one of the clearest signals of pressure on the Rupee and reserves.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'sbp-foreign-exchange-reserves'), 'fx-reserves-2026-07-05', 'SBP Foreign Exchange Reserves (Weekly)', '2026-07-05', '16:30', '$11.4B', '$11.5B', null, 'scheduled', 'Medium', 'The State Bank''s weekly statement of liquid foreign reserves — the buffer available to defend the Rupee and meet external obligations.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'kse-100-weekly-market-review'), 'kse-2026-07-07', 'KSE-100 Weekly Market Review', '2026-07-07', '17:00', '+0.6% WoW', null, null, 'scheduled', 'Low', 'A weekly wrap-up of the Pakistan Stock Exchange''s benchmark KSE-100 index performance and the sectors driving it.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'spi-weekly-inflation-release'), 'spi-2026-07-09', 'SPI Weekly Inflation Release', '2026-07-09', '12:00', '+0.20% WoW', '+0.18% WoW', null, 'scheduled', 'Low', 'PBS''s weekly Sensitive Price Indicator — a fast-moving read on prices for a basket of essential, frequently-purchased items, well ahead of the monthly CPI print.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'cpi-inflation-release'), 'cpi-2026-07-10', 'CPI Inflation Release (June 2026)', '2026-07-10', '12:00', '6.8% YoY', '6.4% YoY', null, 'scheduled', 'High', 'PBS''s headline Consumer Price Index — the most-watched single inflation number, and the figure SBP weighs most heavily when setting the policy rate.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'sbp-foreign-exchange-reserves'), 'fx-reserves-2026-07-12', 'SBP Foreign Exchange Reserves (Weekly)', '2026-07-12', '16:30', '$11.5B', '$11.6B', null, 'scheduled', 'Medium', 'The State Bank''s weekly statement of liquid foreign reserves — the buffer available to defend the Rupee and meet external obligations.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'current-account-balance'), 'current-account-2026-07-15', 'Current Account Balance (June 2026)', '2026-07-15', '17:00', '-$0.4B', '-$0.2B', null, 'scheduled', 'Medium', 'SBP''s monthly current account balance — the broadest measure of money flowing in versus out of Pakistan internationally, and a key driver of reserve and currency stability.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'spi-weekly-inflation-release'), 'spi-2026-07-16', 'SPI Weekly Inflation Release', '2026-07-16', '12:00', '+0.18% WoW', '+0.15% WoW', null, 'scheduled', 'Low', 'PBS''s weekly Sensitive Price Indicator — a fast-moving read on prices for a basket of essential, frequently-purchased items, well ahead of the monthly CPI print.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'worker-remittances'), 'remittances-2026-07-18', 'Worker Remittances (June 2026)', '2026-07-18', '16:00', '$3.1B', '$3.2B', null, 'scheduled', 'Medium', 'SBP''s monthly worker remittance inflows — money sent home by overseas Pakistanis, a major source of foreign exchange alongside exports.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'sbp-foreign-exchange-reserves'), 'fx-reserves-2026-07-19', 'SBP Foreign Exchange Reserves (Weekly)', '2026-07-19', '16:30', '$11.6B', '$11.7B', null, 'scheduled', 'Medium', 'The State Bank''s weekly statement of liquid foreign reserves — the buffer available to defend the Rupee and meet external obligations.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'kse-100-weekly-market-review'), 'kse-2026-07-21', 'KSE-100 Weekly Market Review', '2026-07-21', '17:00', '-0.4% WoW', null, null, 'scheduled', 'Low', 'A weekly wrap-up of the Pakistan Stock Exchange''s benchmark KSE-100 index performance and the sectors driving it.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'sbp-monetary-policy-committee-meeting'), 'sbp-mpc-2026-07-27', 'SBP Monetary Policy Committee Meeting', '2026-07-27', '14:00', '11.5%', null, null, 'scheduled', 'High', 'The State Bank''s policy rate decision — the single most market-moving recurring event on this calendar, setting the benchmark cost of borrowing across the economy. First MPC meeting of FY27, per SBP''s official advance calendar; same-day Monetary Policy Statement, analyst briefing the following day (Jul 28), and SBP''s first Monetary Policy Report of FY27 due Aug 10.', 'confirmed')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'spi-weekly-inflation-release'), 'spi-2026-07-23', 'SPI Weekly Inflation Release', '2026-07-23', '12:00', '+0.15% WoW', '+0.14% WoW', null, 'scheduled', 'Low', 'PBS''s weekly Sensitive Price Indicator — a fast-moving read on prices for a basket of essential, frequently-purchased items, well ahead of the monthly CPI print.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'sbp-foreign-exchange-reserves'), 'fx-reserves-2026-07-26', 'SBP Foreign Exchange Reserves (Weekly)', '2026-07-26', '16:30', '$11.7B', '$11.8B', null, 'scheduled', 'Medium', 'The State Bank''s weekly statement of liquid foreign reserves — the buffer available to defend the Rupee and meet external obligations.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'spi-weekly-inflation-release'), 'spi-2026-07-30', 'SPI Weekly Inflation Release', '2026-07-30', '12:00', '+0.14% WoW', '+0.12% WoW', null, 'scheduled', 'Low', 'PBS''s weekly Sensitive Price Indicator — a fast-moving read on prices for a basket of essential, frequently-purchased items, well ahead of the monthly CPI print.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'trade-balance'), 'trade-balance-2026-07-31', 'Trade Balance (July 2026)', '2026-07-31', '17:00', '-$1.9B', '-$2.0B', null, 'scheduled', 'Medium', 'PBS''s monthly goods trade balance — exports minus imports — one of the clearest signals of pressure on the Rupee and reserves.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'sbp-foreign-exchange-reserves'), 'fx-reserves-2026-08-02', 'SBP Foreign Exchange Reserves (Weekly)', '2026-08-02', '16:30', '$11.8B', '$11.9B', null, 'scheduled', 'Medium', 'The State Bank''s weekly statement of liquid foreign reserves — the buffer available to defend the Rupee and meet external obligations.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'gdp-growth-release'), 'gdp-2026-08-07', 'GDP Growth Release (FY2025-26 Provisional)', '2026-08-07', '16:00', '2.7%', '3.2%', null, 'scheduled', 'High', 'PBS''s provisional annual GDP growth estimate — the headline number used to judge whether the economy is creating jobs and raising incomes fast enough.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'cpi-inflation-release'), 'cpi-2026-08-10', 'CPI Inflation Release (July 2026)', '2026-08-10', '12:00', '6.4% YoY', '6.1% YoY', null, 'scheduled', 'High', 'PBS''s headline Consumer Price Index — the most-watched single inflation number, and the figure SBP weighs most heavily when setting the policy rate.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'current-account-balance'), 'current-account-2026-08-14', 'Current Account Balance (July 2026)', '2026-08-14', '17:00', '-$0.2B', '-$0.3B', null, 'scheduled', 'Medium', 'SBP''s monthly current account balance — the broadest measure of money flowing in versus out of Pakistan internationally, and a key driver of reserve and currency stability.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'sbp-monetary-policy-committee-meeting'), 'sbp-mpc-2026-09-14', 'SBP Monetary Policy Committee Meeting', '2026-09-14', '14:00', null, null, null, 'scheduled', 'High', 'The State Bank''s policy rate decision — the single most market-moving recurring event on this calendar, setting the benchmark cost of borrowing across the economy. Second MPC meeting of FY27, per SBP''s official advance calendar; same-day statement and analyst briefing (no press conference this cycle — SBP holds governor press conferences only after the Jul/Oct/Jan/Apr meetings).', 'confirmed')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'sbp-monetary-policy-committee-meeting'), 'sbp-mpc-2026-10-26', 'SBP Monetary Policy Committee Meeting', '2026-10-26', '14:00', null, null, null, 'scheduled', 'High', 'The State Bank''s policy rate decision — the single most market-moving recurring event on this calendar, setting the benchmark cost of borrowing across the economy. Third MPC meeting of FY27, per SBP''s official advance calendar; same-day statement and governor press conference, analyst briefing the following day (Oct 27).', 'confirmed')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'sbp-monetary-policy-committee-meeting'), 'sbp-mpc-2026-12-14', 'SBP Monetary Policy Committee Meeting', '2026-12-14', '14:00', null, null, null, 'scheduled', 'High', 'The State Bank''s policy rate decision — the single most market-moving recurring event on this calendar, setting the benchmark cost of borrowing across the economy. Fourth MPC meeting of FY27, per SBP''s official advance calendar; same-day statement and analyst briefing (no press conference this cycle).', 'confirmed')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'sbp-monetary-policy-committee-meeting'), 'sbp-mpc-2027-01-25', 'SBP Monetary Policy Committee Meeting', '2027-01-25', '14:00', null, null, null, 'scheduled', 'High', 'The State Bank''s policy rate decision — the single most market-moving recurring event on this calendar, setting the benchmark cost of borrowing across the economy. Fifth MPC meeting of FY27, per SBP''s official advance calendar; same-day statement and governor press conference, analyst briefing the following day (Jan 26); SBP''s second Monetary Policy Report of FY27 due Feb 8.', 'confirmed')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'sbp-monetary-policy-committee-meeting'), 'sbp-mpc-2027-03-08', 'SBP Monetary Policy Committee Meeting', '2027-03-08', '14:00', null, null, null, 'scheduled', 'High', 'The State Bank''s policy rate decision — the single most market-moving recurring event on this calendar, setting the benchmark cost of borrowing across the economy. Sixth MPC meeting of FY27, per SBP''s official advance calendar; same-day statement and analyst briefing (no press conference this cycle).', 'confirmed')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'sbp-monetary-policy-committee-meeting'), 'sbp-mpc-2027-04-26', 'SBP Monetary Policy Committee Meeting', '2027-04-26', '14:00', null, null, null, 'scheduled', 'High', 'The State Bank''s policy rate decision — the single most market-moving recurring event on this calendar, setting the benchmark cost of borrowing across the economy. Seventh MPC meeting of FY27, per SBP''s official advance calendar; same-day statement and governor press conference, analyst briefing the following day (Apr 27).', 'confirmed')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'sbp-monetary-policy-committee-meeting'), 'sbp-mpc-2027-06-17', 'SBP Monetary Policy Committee Meeting', '2027-06-17', '14:00', null, null, null, 'scheduled', 'High', 'The State Bank''s policy rate decision — the single most market-moving recurring event on this calendar, setting the benchmark cost of borrowing across the economy. Eighth and final MPC meeting of FY27, per SBP''s official advance calendar; same-day statement and analyst briefing (no press conference this cycle).', 'confirmed')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'pakistan-economic-survey'), 'economic-survey-2027-06-05', 'Pakistan Economic Survey 2026-27', '2027-06-05', '15:00', 'Economic Survey 2025-26', null, null, 'scheduled', 'High', 'The Ministry of Finance''s annual stock-take of the economy — growth, inflation, fiscal and external accounts — released the day before the federal budget and used to frame it.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'federal-budget'), 'federal-budget-2027-06-06', 'Federal Budget 2027-28 Presentation', '2027-06-06', '17:00', 'Federal Budget 2026-27', null, null, 'scheduled', 'High', 'The federal government''s annual budget speech in the National Assembly — next year''s tax measures, spending allocations, and fiscal targets, all set in this single sitting.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'treasury-bill-auction'), 'tbill-auction-2026-07-02', 'Treasury Bill Auction (3M)', '2026-07-02', '11:00', '11.20%', '11.10%', null, 'scheduled', 'Medium', 'SBP''s fortnightly 3-month Treasury Bill auction — the cut-off yield is the clearest live read on what the market expects from the next SBP policy rate decision.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'core-inflation-release'), 'core-inflation-2026-07-10', 'Core Inflation Release (June 2026)', '2026-07-10', '12:00', '9.8% YoY', '9.5% YoY', null, 'scheduled', 'High', 'PBS''s core (Urban NFNE) inflation — CPI with volatile food and energy prices stripped out, the measure SBP weighs most heavily for the underlying, persistent inflation trend.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'large-scale-manufacturing-lsm-growth'), 'lsm-2026-07-18', 'Large Scale Manufacturing (LSM) Growth (May 2026)', '2026-07-18', '16:00', '1.2% YoY', '1.8% YoY', null, 'scheduled', 'Medium', 'PBS''s Large Scale Manufacturing index — a monthly, timelier proxy for industrial output growth than the annual GDP release.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'pib-auction'), 'pib-auction-2026-07-24', 'PIB Auction (3Y)', '2026-07-24', '11:00', '12.10%', '12.00%', null, 'scheduled', 'Medium', 'SBP''s Pakistan Investment Bond auction — the cut-off yield on longer-dated government debt, reflecting investor expectations for inflation and rates further out than T-Bills.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'government-debt-release'), 'debt-2026-07-28', 'Government Debt Release (Q4 FY2025-26)', '2026-07-28', '17:00', 'Rs 76.5T', 'Rs 78.0T', null, 'scheduled', 'High', 'SBP''s quarterly statement of total government debt — domestic and external combined — a key gauge of fiscal sustainability and future debt-servicing pressure.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'psx-holiday-calendar'), 'psx-holiday-2026-08-14', 'PSX Holiday Calendar (Independence Day)', '2026-08-14', '00:00', null, null, null, 'scheduled', 'Low', 'Pakistan Stock Exchange is closed for trading — no KSE-100 session today.', 'estimated')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'cpi-inflation-release'), 'cpi-2026-04-10', 'CPI Inflation Release (April 2026)', '2026-04-10', '12:00', '7.4% YoY', '7.0% YoY', '7.1% YoY', 'released', 'High', 'PBS''s headline Consumer Price Index — the most-watched single inflation number, and the figure SBP weighs most heavily when setting the policy rate.', 'confirmed')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'gdp-growth-release'), 'gdp-2026-04-15', 'GDP Growth Release (FY2024-25 Final)', '2026-04-15', '16:00', '2.62%', '3.0%', '3.18%', 'released', 'High', 'PBS''s final, revised annual GDP growth figure for FY2024-25 — the headline number used to judge whether the economy is creating jobs and raising incomes fast enough.', 'confirmed')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'sbp-monetary-policy-committee-meeting'), 'sbp-mpc-2026-04-27', 'SBP Monetary Policy Committee Meeting', '2026-04-27', '14:00', '10.5%', '10.5% (hold expected)', '11.5% (hiked +100bps)', 'released', 'High', 'The State Bank''s policy rate decision — the single most market-moving recurring event on this calendar, setting the benchmark cost of borrowing across the economy. A surprise hike — analysts had expected a hold — as accelerating inflation and oil-price volatility pushed the MPC to tighten ahead of expectations.', 'confirmed')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'current-account-balance'), 'current-account-2026-05-15', 'Current Account Balance (April 2026)', '2026-05-15', '17:00', '-$0.6B', '-$0.4B', '-$0.5B', 'released', 'Medium', 'SBP''s monthly current account balance — the broadest measure of money flowing in versus out of Pakistan internationally, and a key driver of reserve and currency stability.', 'confirmed')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'cpi-inflation-release'), 'cpi-2026-05-10', 'CPI Inflation Release (May 2026)', '2026-05-10', '12:00', '7.1% YoY', '6.9% YoY', '6.8% YoY', 'released', 'High', 'PBS''s headline Consumer Price Index — the most-watched single inflation number, and the figure SBP weighs most heavily when setting the policy rate.', 'confirmed')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'sbp-monetary-policy-committee-meeting'), 'sbp-mpc-2026-06-15', 'SBP Monetary Policy Committee Meeting', '2026-06-15', '14:00', '11.5%', '11.5% (hold expected)', '11.5% (held)', 'released', 'High', 'The State Bank''s policy rate decision — the single most market-moving recurring event on this calendar, setting the benchmark cost of borrowing across the economy. The MPC held steady in its final FY26 review, judging the April hike''s tightening as still appropriate given GDP growth near 3.7% and reserves rebuilding toward $17.2B.', 'confirmed')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'sbp-foreign-exchange-reserves'), 'fx-reserves-2026-06-18', 'SBP Foreign Exchange Reserves (Weekly)', '2026-06-18', '16:30', '$10.9B', '$11.0B', '$11.0B', 'released', 'Medium', 'The State Bank''s weekly statement of liquid foreign reserves — the buffer available to defend the Rupee and meet external obligations.', 'confirmed')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'treasury-bill-auction'), 'tbill-auction-2026-04-16', 'Treasury Bill Auction (3M)', '2026-04-16', '11:00', '11.50%', '11.30%', '11.25%', 'released', 'Medium', 'SBP''s fortnightly 3-month Treasury Bill auction — the cut-off yield is the clearest live read on what the market expects from the next SBP policy rate decision.', 'confirmed')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'core-inflation-release'), 'core-inflation-2026-04-10', 'Core Inflation Release (March 2026)', '2026-04-10', '12:00', '10.1% YoY', '9.9% YoY', '9.8% YoY', 'released', 'High', 'PBS''s core (Urban NFNE) inflation — CPI with volatile food and energy prices stripped out, the measure SBP weighs most heavily for the underlying, persistent inflation trend.', 'confirmed')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'large-scale-manufacturing-lsm-growth'), 'lsm-2026-04-18', 'Large Scale Manufacturing (LSM) Growth (February 2026)', '2026-04-18', '16:00', '0.5% YoY', '1.0% YoY', '1.3% YoY', 'released', 'Medium', 'PBS''s Large Scale Manufacturing index — a monthly, timelier proxy for industrial output growth than the annual GDP release.', 'confirmed')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'pib-auction'), 'pib-auction-2026-04-24', 'PIB Auction (3Y)', '2026-04-24', '11:00', '12.40%', '12.20%', '12.15%', 'released', 'Medium', 'SBP''s Pakistan Investment Bond auction — the cut-off yield on longer-dated government debt, reflecting investor expectations for inflation and rates further out than T-Bills.', 'confirmed')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'government-debt-release'), 'debt-2026-04-28', 'Government Debt Release (Q3 FY2025-26)', '2026-04-28', '17:00', 'Rs 74.0T', 'Rs 75.5T', 'Rs 75.8T', 'released', 'High', 'SBP''s quarterly statement of total government debt — domestic and external combined — a key gauge of fiscal sustainability and future debt-servicing pressure.', 'confirmed')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
