-- Corrects the FY27 SBP Monetary Policy Committee schedule against SBP's
-- official advance calendar (published 2026-06-23/24,
-- https://www.sbp.org.pk/m_policy/mp-calendar.asp), confirmed across
-- multiple independent financial press reports (Dawn, Business Recorder,
-- TechJuice, ICCI) citing the same SBP announcement.
--
-- The mock-data seed (0003) was written before that calendar existed, so
-- it estimated the first two FY27 meetings rather than sourcing them —
-- 2026-07-22 (should be 2026-07-27) and 2026-09-09 (should be 2026-09-14).
-- Those two slugs are deleted outright rather than updated in place: this
-- migration also adds the remaining 6 FY27 meetings as brand-new rows, and
-- simply re-running 0003 (an `on conflict (slug) do update`) would leave
-- the old, now-incorrect slugs sitting alongside the new correct ones as
-- duplicates, since upserts never remove rows whose slug no longer appears
-- in the source data.
--
-- Run AFTER 0003_economic_calendar_seed.sql has been applied at least once.
-- Idempotent: safe to re-run.

delete from public.economic_events where slug in ('sbp-mpc-2026-07-22', 'sbp-mpc-2026-09-09');

insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'sbp-monetary-policy-committee-meeting'), 'sbp-mpc-2026-07-27', 'SBP Monetary Policy Committee Meeting', '2026-07-27', '14:00', '11.5%', null, null, 'scheduled', 'High', 'The State Bank''s policy rate decision — the single most market-moving recurring event on this calendar, setting the benchmark cost of borrowing across the economy. First MPC meeting of FY27, per SBP''s official advance calendar; same-day Monetary Policy Statement, analyst briefing the following day (Jul 28), and SBP''s first Monetary Policy Report of FY27 due Aug 10.', 'confirmed')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'sbp-monetary-policy-committee-meeting'), 'sbp-mpc-2026-09-14', 'SBP Monetary Policy Committee Meeting', '2026-09-14', '14:00', null, null, null, 'scheduled', 'High', 'The State Bank''s policy rate decision — the single most market-moving recurring event on this calendar, setting the benchmark cost of borrowing across the economy. Second MPC meeting of FY27, per SBP''s official advance calendar; same-day statement and analyst briefing (no press conference this cycle — SBP holds governor press conferences only after the Jul/Oct/Jan/Apr meetings).', 'confirmed')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'sbp-monetary-policy-committee-meeting'), 'sbp-mpc-2026-10-26', 'SBP Monetary Policy Committee Meeting', '2026-10-26', '14:00', null, null, null, 'scheduled', 'High', 'The State Bank''s policy rate decision — the single most market-moving recurring event on this calendar, setting the benchmark cost of borrowing across the economy. Third MPC meeting of FY27, per SBP''s official advance calendar; same-day statement and governor press conference, analyst briefing the following day (Oct 27).', 'confirmed')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'sbp-monetary-policy-committee-meeting'), 'sbp-mpc-2026-12-14', 'SBP Monetary Policy Committee Meeting', '2026-12-14', '14:00', null, null, null, 'scheduled', 'High', 'The State Bank''s policy rate decision — the single most market-moving recurring event on this calendar, setting the benchmark cost of borrowing across the economy. Fourth MPC meeting of FY27, per SBP''s official advance calendar; same-day statement and analyst briefing (no press conference this cycle).', 'confirmed')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'sbp-monetary-policy-committee-meeting'), 'sbp-mpc-2027-01-25', 'SBP Monetary Policy Committee Meeting', '2027-01-25', '14:00', null, null, null, 'scheduled', 'High', 'The State Bank''s policy rate decision — the single most market-moving recurring event on this calendar, setting the benchmark cost of borrowing across the economy. Fifth MPC meeting of FY27, per SBP''s official advance calendar; same-day statement and governor press conference, analyst briefing the following day (Jan 26); SBP''s second Monetary Policy Report of FY27 due Feb 8.', 'confirmed')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'sbp-monetary-policy-committee-meeting'), 'sbp-mpc-2027-03-08', 'SBP Monetary Policy Committee Meeting', '2027-03-08', '14:00', null, null, null, 'scheduled', 'High', 'The State Bank''s policy rate decision — the single most market-moving recurring event on this calendar, setting the benchmark cost of borrowing across the economy. Sixth MPC meeting of FY27, per SBP''s official advance calendar; same-day statement and analyst briefing (no press conference this cycle).', 'confirmed')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'sbp-monetary-policy-committee-meeting'), 'sbp-mpc-2027-04-26', 'SBP Monetary Policy Committee Meeting', '2027-04-26', '14:00', null, null, null, 'scheduled', 'High', 'The State Bank''s policy rate decision — the single most market-moving recurring event on this calendar, setting the benchmark cost of borrowing across the economy. Seventh MPC meeting of FY27, per SBP''s official advance calendar; same-day statement and governor press conference, analyst briefing the following day (Apr 27).', 'confirmed')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
insert into public.economic_events (series_id, slug, title, event_date, event_time, previous_value, forecast_value, actual_value, status, importance, description, data_confidence)
values ((select id from public.economic_event_series where slug = 'sbp-monetary-policy-committee-meeting'), 'sbp-mpc-2027-06-17', 'SBP Monetary Policy Committee Meeting', '2027-06-17', '14:00', null, null, null, 'scheduled', 'High', 'The State Bank''s policy rate decision — the single most market-moving recurring event on this calendar, setting the benchmark cost of borrowing across the economy. Eighth and final MPC meeting of FY27, per SBP''s official advance calendar; same-day statement and analyst briefing (no press conference this cycle).', 'confirmed')
on conflict (slug) do update set series_id = excluded.series_id, title = excluded.title, event_date = excluded.event_date, event_time = excluded.event_time, previous_value = excluded.previous_value, forecast_value = excluded.forecast_value, actual_value = excluded.actual_value, status = excluded.status, importance = excluded.importance, description = excluded.description, data_confidence = excluded.data_confidence, updated_at = now();
