-- Migration 0024: Live slug previous_value and title corrections
--
-- Problem: Migrations 0022 and 0023 targeted seed-file slugs (e.g.
-- cpi-2026-07-10, current-account-2026-07-15) but the live DB contains slugs
-- generated by migration 0013's rolling calendar formula (e.g. cpi-2026-07-01,
-- current-account-2026-07-16). All UPDATE statements in those migrations were
-- NO-OPS against the live DB. This migration targets the ACTUAL live slugs.
--
-- Verified live DB state before this migration (2026-07-01):
--   cpi-2026-07-01:         status=scheduled, prev='6.8% YoY'   → should cascade from cpi-2026-06-10 actual='11.7% YoY'
--   core-inflation-2026-07-01: status=scheduled, prev='9.8% YoY' → should cascade from core-inflation-2026-06-10 actual='9.0% YoY'
--   remittances-2026-07-09: status=scheduled, prev='$3.1B'      → should cascade from remittances-2026-06-10 actual='$3.53B'
--   current-account-2026-07-16: status=scheduled, prev='-$0.4B' → should cascade from current-account-2026-06-15 actual='$-0.28B'
--
-- Title convention: BoP series (remittances, current-account) use lagMonths=2
-- in the period validator. The migration 0013 rolling calendar stored
-- reference_period one month ahead of the true data period (a formula
-- workaround — see generate_next_occurrence()). The stored titles reflect the
-- reference_period month, not the actual data month, causing misleading labels.
-- This migration corrects only the title strings; reference_period is left
-- unchanged because the rolling calendar formula depends on it.
--
-- Part A — previous_value corrections (4 events, scheduled only)
-- Part B — title corrections for BoP events (3 events, any status)

-- ── Part A: previous_value corrections ───────────────────────────────────────

-- A-1: CPI July 1 — cascade from June 10 actual (11.7% YoY)
update public.economic_events
set    previous_value = '11.7% YoY'
where  slug = 'cpi-2026-07-01'
  and  status = 'scheduled'
  and  previous_value = '6.8% YoY';

-- A-2: Core Inflation July 1 — cascade from June 10 actual (9.0% YoY)
update public.economic_events
set    previous_value = '9.0% YoY'
where  slug = 'core-inflation-2026-07-01'
  and  status = 'scheduled'
  and  previous_value = '9.8% YoY';

-- A-3: Remittances July 9 — cascade from June 10 actual ($3.53B)
update public.economic_events
set    previous_value = '$3.53B'
where  slug = 'remittances-2026-07-09'
  and  status = 'scheduled'
  and  previous_value = '$3.1B';

-- A-4: Current Account July 16 — cascade from June 15 actual ($-0.28B)
update public.economic_events
set    previous_value = '$-0.28B'
where  slug = 'current-account-2026-07-16'
  and  status = 'scheduled'
  and  previous_value = '-$0.4B';

-- ── Part B: title corrections for BoP events ─────────────────────────────────
--
-- The rolling calendar stores reference_period one month ahead of the true
-- data period for lagMonths=2 series (required by generate_next_occurrence()
-- to produce the correct next-release date). Titles derived from that
-- reference_period therefore show the wrong month. Corrections:
--   July 9  remittances: ref_period=Jun → title was "June 2026", data is May
--   July 16 current-account: ref_period=Jun → title was "June 2026", data is May
--   Aug 17  current-account: ref_period=Jul → title was "July 2026", data is June

-- B-1: Remittances July 9 — data is May 2026, not June
update public.economic_events
set    title = 'Worker Remittances (May 2026)'
where  slug = 'remittances-2026-07-09'
  and  title = 'Worker Remittances (June 2026)';

-- B-2: Current Account July 16 — data is May 2026, not June
update public.economic_events
set    title = 'Current Account Balance (May 2026)'
where  slug = 'current-account-2026-07-16'
  and  title = 'Current Account Balance (June 2026)';

-- B-3: Current Account August 17 — data is June 2026, not July
update public.economic_events
set    title = 'Current Account Balance (June 2026)'
where  slug = 'current-account-2026-08-17'
  and  title = 'Current Account Balance (July 2026)';
